### ISSUE TITLE
Wahoo should detect when an update is available and notify users.

### ISSUE THREAD

**Issue by bucaran** [bucaran/wahoo#13]

**Comment by gretel** [comment]
how about timestamp in a universal variable and check for updates every eventually configurable interval

**Comment by bucaran** [comment]
The best solution is to store the latest version as a tag on GitHub or in a server somewhere and check against that every time the session starts. But it would add a delay to the startup :(

**Comment by bucaran** [comment]
I vote to close this down. If someone really wants this feature a plugin could be made that check this for you.

**Comment by gretel** [comment]
i have a prototype plugin working but i do need some assitance on how to integrate nicely. catch me on gitter if you can. regards

**Comment by bucaran** [comment]
Sounds good. Do you have any code? Would you mind pasting that here to entice an open discussion?

Thanks.

**Comment by gretel** [comment]
```
# automagically check for updates on 'wa_check_upd' event
function init --on-event init_upd
  function wa_upd_stamp
    set -U wa_upd_comp (math (date +%s)+$wa_upd_interval) # not now but in $seconds
  end
  function wa_upd_trigger
    block --local # prevent concurrency
    wa_upd_stamp # update timestamp
    echo "🚀  Updating Wahoo ..."
    wa_update # update wahoo
    echo "🚀  Next update run in $wa_upd_interval seconds."
  end
  function wa_upd_check --on-event wa_check_upd
    # check for interval
    if test $wa_upd_comp -lt (date +%s)
      # overflow
      wa_upd_trigger
    end # nope
  end
  set -U wa_upd_interval 300 # TODO: abstraction
  # check if set previously
  if test -z $wa_upd_comp
    wa_upd_stamp # initialize comparator
  end
end
```

**Comment by bucaran** [comment]
Great. Make a package out of it and voila.

**Comment by bpinto** [comment]
I'd like to go back to old code style:

1. One function per file.
2. Use `.` for namespacing: `wa_upd_interval` => `wa.update_interval`

**Comment by bucaran** [comment]
> One function per file.

Yes.

> Use . for namespacing: wa_upd_interval => wa.update_interval

I am not 100% sure about this bit. I like how it looks though, but it would require modifying core drastically.

Also https://github.com/bucaran/wahoo/blob/master/CONTRIBUTING.md

**Comment by gretel** [comment]
@bpinto i don't get why `one function per file` would change anything for the better. could you please point me to the according guideline?

**Comment by bpinto** [comment]
Having one function per file is how fish "expects" things to be:

> It is very important that function definition files only contain the definition for the specified function and nothing else. Otherwise, it is possible that autoloading a function files requires that the function already be loaded, which creates a circular dependency.

http://fishshell.com/docs/current/#syntax-function-autoloading

**Comment by bpinto** [comment]
@bucaran using `.` for namespace highly increase the code readability imo.

**Comment by bucaran** [comment]
@bpinto :+1: Let's add to CONTRIBUTING accordingly. Can you come up with some rules, add and PR?

**Comment by bpinto** [comment]
:+1:
