### ISSUE TITLE
Screencasts

### ISSUE THREAD

**Issue by bucaran** [bucaran/wahoo#14]
![iar](https://cloud.githubusercontent.com/assets/8317250/7823513/eb7bb17a-0436-11e5-847f-9f2641402c20.gif)

**Comment by bucaran** [comment]
![sub](https://cloud.githubusercontent.com/assets/8317250/7828606/9cedfb32-0470-11e5-952a-293a5508ee18.gif)

**Comment by hauleth** [comment]
There is great tool for that https://asciinema.org/

**Comment by bucaran** [comment]
@hauleth Thanks! It looks amazing.

**Comment by bucaran** [comment]
Cool https://github.com/bucaran/wahoo/wiki/Screencasts

**Comment by hauleth** [comment]
👍

--
Łukasz Jan Niemier

Dnia 3 cze 2015 o godz. 20:50 Jorge Bucaran <notifications@github.com> napisał(a):
