### ISSUE TITLE
wa get package form git directly

### ISSUE THREAD

**Issue by TeddyDD** [bucaran/wahoo#27]
It would allow to install packages from github/gitlab etc repos instead from db
Something like ```go get```
example

```wa get oh-my-fish/plugin-extract``` for github
```wa get https://gitlab.com/jacaetevha/oh-my-fish.git``` for other git hosts

**Comment by bucaran** [comment]
Thanks! This is such an obviously missing feature. Shipping soon.

One thing though, (obviously) there is no way to provide fish _completions_ or verify the package would work with Wahoo, but it's definitely useful to have.

**Comment by TeddyDD** [comment]
This will also need some syntax to distinguish packages and themes

**Comment by bucaran** [comment]
@TeddyDD 

What about this?

```fish
wa get bitbucket.com/ted/stuff # => $WAHOO_PATH/stuff/...
wa get bitbucket.com/ted/stuff mystuff # => $WAHOO_PATH/mystuff/...
wa get bitbucket.com/ted/stuff pkg # => $WAHOO_PATH/stuff/...
wa get bitbucket.com/ted/wa-sexy themes/sexy # => $WAHOO_PATH/themes/sexy...
```

**Comment by TeddyDD** [comment]
@bucaran Looks nice and generic. What's the difference between 
```
bitbucket.com/ted/stuff mystuff # => $WAHOO_PATH/mystuff/...
bitbucket.com/ted/stuff pkg # => $WAHOO_PATH/stuff/...
```
?

**Comment by bucaran** [comment]
Indeed that was a typo:

It should read

```fish
wa get bitbucket.com/ted/stuff pkg # => $WAHOO_PATH/pkg/stuff/...
```

**Comment by TeddyDD** [comment]
Oh ok :) Looks really good

**Comment by brmzk** [comment]
:+1:

**Comment by bucaran** [comment]
@TeddyDD @brmzk 

Basic functionality was implemented. Since, `wa g ...` takes a list of arguments (that could be pkg or theme names and now URLs) it was too difficult to allow users to choose where to clone the remote repos, but now it's possible to do this:

```
wa g url1 url2 url3
```

and it will all go into `$WAHOO_PATH/pkg`, which is pretty nifty.
