### ISSUE TITLE
default fish completions [question]

### ISSUE THREAD

**Issue by TeddyDD** [bucaran/wahoo#28]
Not sure if this is default behaviour of Fish or my distro specific problem or Wahoo issue.

After installation my ```$fish_complete_path``` does not contain  ```/usr/share/fish/completions```
I had to add this manually via custom package. 

I'm using Fish since yesterday so if this is stupid question let me know :wink:

**Comment by bucaran** [comment]
Nice catch! Just fixed it and pushed.

**Comment by TeddyDD** [comment]
Wow, that was fast :D Thanks :)

**Comment by bucaran** [comment]
`$fish_complete_path` is being correctly handled now, so you probably don't need that custom plugin you were talking about. BTW if you have ideas for plugins, please let me know your thoughts in #18.
