### ISSUE TITLE
command to turn packages on and off without removing them

### ISSUE THREAD

**Issue by TeddyDD** [bucaran/wahoo#29]
Something like ```wa off package1``` ```wa on package3```
It could be done by renaming ```.fish``` files to something like ```.fish.off```

**Comment by bucaran** [comment]
Good call. Of course I had considered this oroginally, but the overhead of installing / uninstalling a package is so low I left it out. If you don't want to use a plugin why not simple remove it?

**Comment by TeddyDD** [comment]
Custom plugins. For example I basically porting my old .bashrc While splitting it to few custom pkgs (Golang env variables is one pkg, my personal aliases is another etc.) Most of this custom plugins are not on git yet (I'm lazy ) Turning them off might be useful especially while there still  in development. To be honest wa's ability to quickly create pkg's and keep my shell customizations separated nice and clean is a killer feature :)

If you prefer to keep ```wa``` as simple as possible  with is good, this feature  might be implemented as plugin (this would be even better)

**Comment by bucaran** [comment]
Gotcha :smile: 

Ideally people would create a package, but I also think you have a valid use case so here is my proposal.

As you can imagine, there are a few ways we could implement this, a very simple way could be using another `$WAHOO` like variable, something like `$WAHOO_IGNORE` where you can set what plugins you want to ignore. Do you think you will be switching packages on and off a lot? If you are just testing a plugin you can always use the `refresh` global function to reload everything.

###### Note

BTW don't forget you can edit ` ~/.config/fish/config.fish` and set `$WAHOO_CUSTOM` to point to your dotfiles directory. If you create an `init.fish` file and drop it in `$WAHOO_CUSTOM/` it will be run by Wahoo at the end of the bootstrap process.

**Comment by TeddyDD** [comment]
Well this feature would be useful mainly while developing pkgs to avoid clutter in your nornal work environment ;) Its rather low priority request. Another way this could be implemented is we coud create some dummy file in specific package directory that marks package as  "wip". That packages would be loaded explicitly by user

**Comment by bucaran** [comment]
> Another way this could be implemented is we coud create some dummy file in specific package directory that marks package as "wip". That packages would be loaded explicitly by user

I like this and the idea of loading plugins manually :+1:

**Comment by bucaran** [comment]
> Remove any packages you wish to turn off using wa remove <package name>. If you prefer to ignore packages locally without uninstalling them simply set a new global $WAHOO_IGNORE in your ~/.config/fish/config.fish. For example:
>
>set -g WAHOO_IGNORE this that ...

**Comment by bucaran** [comment]
Done.

@TeddyDD 
What do you think?

> Remove any packages you wish to turn off using wa remove <package name>. If you prefer to ignore packages locally without uninstalling them simply set a new global $WAHOO_IGNORE in your ~/.config/fish/config.fish. For example:
>
> `set -g WAHOO_IGNORE this that ...`

**Comment by TeddyDD** [comment]
Awsome :D Thank you!

**Comment by bucaran** [comment]
:+1:
