### ISSUE TITLE
Wahoo errors after update

### ISSUE THREAD

**Issue by TeddyDD** [bucaran/wahoo#30]
ba29e395ea1a337d8ba7337fe13a6d2f62564b97
```
>wa help
wa_list_local_packages: command not found
/home/teddy/.wahoo/pkg/wa/wa.fish (line 56):       wa_list_local_packages | column
                                                   ^
in function 'wa',
	called on standard input,
	with parameter list 'list'

>wa list
wa_list_local_packages: command not found
/home/teddy/.wahoo/pkg/wa/wa.fish (line 56):       wa_list_local_packages | column
                                                   ^
in function 'wa',
	called on standard input,
	with parameter list 'list'```

etc.

**Comment by bucaran** [comment]
This may had to do with breaking changes I introduced in the new version, and wahoo does not immediately refreshes itself after update, but instead it prints `Wahoo is up to date...` or similar. 

Are you still experiencing this?

**Comment by TeddyDD** [comment]
Yep. I even  tried manually pull .wahoo from github. Also I used refresh.

**Comment by bucaran** [comment]
What is your `printf "%s\n" $fish_function_path?`

**Comment by bucaran** [comment]
Check whether the directory structure under `$WAHOO_PATH` looks like this

```
/Users/teddy/.wahoo
├── db/
│   ├── pkg/
│   ├── themes/
├── lib/
│   ├── completions/
│   ├── autoload.fish
│   ├── available.fish
│   ├── basename.fish
│   └── refresh.fish
├── pkg/
│   ├── rbenv/
│   ├── tiny/
│   ├── wa/
├── themes/
│   ├── default/
│   ├── hulk/
├── .gitignore
├── .travis.yml
├── LICENSE
├── README.md
├── bootstrap.sh
└── init.fish
```

**Comment by bucaran** [comment]
OK, silly bug. The repo is missing everything under `cli/`. Crazy. Will fix this ASAP.

**Comment by TeddyDD** [comment]
Thanks for fixing this. You rock! And sorry for not responding earlier. I'v got finals on university so I'm not able to respond as quickly as I'd like to :wink:

**Comment by bucaran** [comment]
:+1: Good luck on your finals.
