### ISSUE TITLE
git.io/wahoo-doc leads to non extising file on github

### ISSUE THREAD

**Issue by TeddyDD** [bucaran/wahoo#31]
Link in ```wa help``` git.io/wahoo-doc leads to github 404 
I suppose this is wip but it better to open an issue to keep track on that

**Comment by bucaran** [comment]
Good catch. It should point to `git.io/wahoo` since I merged `DOC.md` with the README several commits ago.

**Comment by bucaran** [comment]
Removed this from the source since, we are not using it anymore.
