### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by bucaran** [bucaran/wahoo#32]
Ideas, PRs also welcome.

**Comment by drKraken** [comment]
Suggest to add `CONTRIBUTING.md` file or add Contributing section to `README`.
> Shell/Fish  scripting can have different code styles , so i think it will be great to have description on wat style you have to follow.

**Comment by bucaran** [comment]
[Done](https://github.com/bucaran/wahoo/blob/master/CONTRIBUTING.md).

Thanks @drKraken
