### ISSUE TITLE
test: Missing argument at index 2

### ISSUE THREAD

**Issue by nouse** [bucaran/wahoo#42]
commit a10852e0f79f1ef8430d7ebe4c1798e90a6b303f
fish version: 2.1.2+dfsg1-2

I met this error after every command.
I see many test statements in wahoo, but can't find out which causes this problem.

**Comment by nouse** [comment]
sorry, this issue has disappeared after I updated fish theme.

**Comment by bucaran** [comment]
I am glad you fixed this! Thanks :)
