### ISSUE TITLE
United States of the Fish or the Fellowship of the Fish

### ISSUE THREAD

**Issue by bucaran** [bucaran/wahoo#94]
:bowtie: Dear @wa/developers @wa/owners /collaborators

oh-my-fish/oh-my-fish/issues/507

**Comment by jrobeson** [comment]
I wish you would have let know know this was on the works. Is any of my previous work going to apply?

**Comment by rrosson** [comment]
Curious on what path is going to be taken the pkg or the way of oh-my-fish. One of the reason from going to wahoo from oh-my-fish was the modularization of being to run a command to add features and not have to muck with the config.fish and various other files..

Please keep us end users in the loop as well.

**Comment by bucaran** [comment]
Nothing is going to change for Wahoo users as everything will be the same. Wahoo will essentially replace OMF. Only the name and logo will change.

@jrobeson All of it applies :+1:

**Comment by jrobeson** [comment]
this is exciting news.

**Comment by scorphus** [comment]
Yeah, pretty exciting news! I wonder what the new name is!

**Comment by bucaran** [comment]
The name will be Oh My Fish. Admittedly, Oh My Fish has better SEO than Wahoo :smile:

**Comment by scorphus** [comment]
YAY! Totally agreed.
Em 26/08/2015 04:20, "Jorge Bucaran" <notifications@github.com> escreveu:

**Comment by rrosson** [comment]
Looking for the best way to transition from wahoo to OMF without loosing my customizations I have. Are there any plans of providing migration instructions for users who were wahoo and not OMF?

TIA

**Comment by bucaran** [comment]
@rrosson From the perspective of Wahoo users, the only change is the name. So, you should be able to install OMF and still keep your `.wahoo` directory intact. After you install Oh My Fish!, just move your customizations to `$OMF_CUSTOM` if that's where you keep them.

**Comment by rrosson** [comment]
Just tried to transition to OMF and found that it does not understand OMF_CUSTOM. reverting back to wahoo till this is fixed. Also noticed the pyenv package still reflects WAHOO_CUSTOM in its README. Will start to follow OMF and watch for another opportunity to attempt transition again.

**Comment by bucaran** [comment]
@rrosson Thanks. This will clear up over the next days and I'll keep you posted! :+1:

**Comment by hauleth** [comment]
I doesn't like the migration. Wahoo was better, smaller, more customizable and doesn't make it feel like it is copy of ZSH.

**Comment by jrobeson** [comment]
cooperation is better than competition for something like this. Adjustments can be made to OMF to make it better. If you have any missing features from OMF then please file specific bug reports there.

**Comment by bucaran** [comment]
@hauleth I am working on a new PR that will improve both the current incarnation of OMF and Wahoo as it stands now. Have a look here > https://github.com/fish-shell/oh-my-fish/issues/583

If it goes through it will be for the best to migrate, otherwise I will probably go back to Wahoo or see what I can do.

**Comment by hauleth** [comment]
Also I have impression that Wahoo packages was more modern and suited for new Fish versions, the packages for OMF are a little bit outdated. IMHO it is sad that this project end it's life as I liked it much more than OMF.

**Comment by bucaran** [comment]
@hauleth There is clearly a misunderstanding here. OMF has grown a bit after the merge, but the code is pretty much still 90% Wahoo. OMF plugins are Wahoo plugins. The old OMF is completely gone. 

With the new PR I am talking the direction will change significantly and things will get even simpler. For example, plugins will be able to extend the core commands as well, which means you can customize the CLI to load only the commands that make sense to you.

**Comment by hauleth** [comment]
Yeah I know, but plugins that was created for Wahoo independently (like mine Agnoster theme) are much different (and in most cases more up to date) than "official" OMF's ones.

**Comment by scorphus** [comment]
I think the community would benefit a lot more if we all stop complaining and join forces in the hard work trying and making OMF better each day. Everyone is welcome aboard https://gitter.im/fish-shell/oh-my-fish! :smiley:

**Comment by bucaran** [comment]
@hauleth About the Agnoster theme, I haven't been able to follow up exactly what happened with it. @scorphus Are we using the old one or the new one?

Obviously the people responsible for this plugin should decide which one is the best, and that should be the one we were using at Wahoo for reasons already stated above.

**Comment by scorphus** [comment]
@bucaran: Sorry, I couldn't understand what you meant. Are you talking about the Gitter channel? In that case, the old one redirects to the new one.
